= Contributing

== Building and compiling the Neo4j JDBC driver

JDK 17 and Maven is required. Please run to test and package the project:

[source,bash]
----
./mvnw verify
----

There's a `fast` profile that will skip all the tests and validations:

[source,bash]
----
./mvnw -Dfast package
----

If the cluster integration test is flaky or does not work at all in your build, you can skip it like this without skipping any other integration tests:

[source,bash]
----
./mvnw -DskipClusterIT verify
----

== Tasks

=== Keep the build descriptor (`pom.xml`) sorted

[source,bash]
----
./mvnw sortpom:sort
----

=== Formatting sources / adding headers

When you add new files, you can run

[source,bash]
----
./mvnw license:format
----

to add required headers automatically.

We use https://github.com/spring-io/spring-javaformat[spring-javaformat] to format the source files.

[source,bash]
----
./mvnw spring-javaformat:apply
----

TIP: The Spring Developers write: "The source formatter does not fundamentally change your code. For example, it will not change the order of import statements. It is effectively limited to adding or removing whitespace and line feeds."
     This means the following checkstyle check might still fail.
     Some common errors:
     +
     Static imports, import `javax.*` and `java.*` before others
     +
     Static imports are helpful, yes, but when working with 2 builders in the same project (here jOOQ and Cypher-DSL), they can be quite confusing.

There are plugins for https://github.com/spring-io/spring-javaformat#eclipse[Eclipse] and https://github.com/spring-io/spring-javaformat#intellij-idea[IntelliJ IDEA] and the Checkstyle settings https://github.com/spring-io/spring-javaformat#checkstyle-idea-plugin[can be imported as well].
We took those "as is" and just disabled the lambda check (requiring even single parameters to have parenthesis).

Public classes do require an author tag.
Please add yourself as an `@author` to the `.java` files you added or that modified substantially (more than cosmetic changes).

== Benchkit support

Standalone runner (Java 17 required):

[source,bash]
----
./mvnw -Dfast -am -pl benchkit clean package
TEST_NEO4J_HOST=localhost TEST_NEO4J_PASS=verysecret java -jar benchkit/target/neo4j-jdbc-benchkit-6.0.0-SNAPSHOT.jar
----

Built a Benchkit compliant Docker as follows.

[source,bash]
----
 docker build . -f benchkit/Dockerfile --tag neo4j/neo4j-jdbc-benchkit-backend
 docker run --publish=9000:9000 \
  -e TEST_NEO4J_HOST=host.docker.internal \
  -e TEST_NEO4J_PASS=verysecret neo4j/neo4j-jdbc-benchkit-backend
----

Pick your poison, in both scenarios the following request should work (assuming you have a Neo4j running on your local machine with the given credentials):

[source,bash]
----
curl -X PUT --location "http://localhost:9000/workload" \
    -H "accept: */*" \
    -H "Content-Type: application/json" \
    -d '{
          "method": "executeQuery",
          "database": "",
          "routing": "write",
          "mode": "sequentialSessions",
          "queries": [
            {
              "text": "UNWIND $titles AS title CREATE (n:Movie {title: title}) RETURN n",
              "parameters": {
                "titles": [
                  "Terminator ",
                  "Terminator 2"
                ]
              }
            },
            {
              "text": "UNWIND range(1,10000) AS i CREATE (n:F {i: i}) RETURN n"
            }
          ]
        }'
----

== Conventions

=== Code

Package private by default, no "impl" packages and the like if avoidable.
Public classes must be final unless explicitly designed as SPI.

=== Commits

Please use conventional commits when possible: https://www.conventionalcommits.org/en/v1.0.0/[Conventional Commits].
Two live examples: https://github.com/neo4j-contrib/cypher-dsl[cypher-dsl] and https://github.com/michael-simons/neo4j-migrations[neo4j-migrations].

== Building the documentation

The docs are written with AsciiDoctor inside the `docs` module.
The module is build with Maven.
The `package` goal will process all asciidoc files and bundle them up both as generated site and as an Antora-ready zip archive, ready to be included somewhere else.

[source,bash]
----
./mvnw -Dfast clean package -pl docs -am
----

On JDK21 you can bring up a web-server like this to view the documentation on http://localhost:8000[localhost:8000]

[source,bash]
----
jwebserver -d `pwd`/docs/target/generated-docs/
----

To preview the Antora docs you can run this after the above Maven build succeeds.
The Maven build is necessary so that the version numbers and other references in the source files are processed proper:

[source,bash]
----
npm --prefix etc/antora i
npm --prefix etc/antora run preview
----

The build also provides a zipped version of the Antora module alone, ready to be pushed into another repo under `docs/target/jdbc-manual.zip`.

== Resources

- https://download.oracle.com/otndocs/jcp/jdbc-4_3-mrel3-spec/index.html[JDBC 4.3 Spec]
- https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/java/sql/package-summary.html[Java 17 JDBC API]
- https://docs.oracle.com/javase/tutorial/jdbc/basics/index.html[JDBC Basics] (JDK 8 based, still useful though)
