= Contributing

== Building and compiling the Neo4j JDBC driver

JDK 17 and Maven is required. Please run to test and package the project:

[source,bash]
----
./mvnw verify
----

There's a `fast` profile that will skip all the tests and validations:

[source,bash]
----
./mvnw -Dfast package
----

If the cluster integration test is flaky or does not work at all in your build, you can skip it like this without skipping any other integration tests:

[source,bash]
----
./mvnw -DskipClusterIT verify
----

== Deploying to Maven central and creating GitHub release notes

NOTE: This task can of course be done only from within the Neo4j organisation.

We do use a mixture of the Maven release plugin and https://jreleaser.org[JReleaser].
Using the deploy-plugin is more complicated in a CI pipeline, as it requires writing down credentials to Maven central somewhere in a `settings.xml` file.
JReleaser is configurable completely via environmental properties and does all the orchestration for us.
We neither use the Maven GPG plugin, as JReleaser offers the ability to also sign our artifacts via GPG as part of the deploy-step, thus avoiding another medium break.

The release itself and the staging of the artifacts is done via the release plugin:

[source,bash]
----
./mvnw -e --no-transfer-progress --batch-mode \
  -DskipTestsDuringRelease \
  -Dtag=X.Y.Z \
  -DreleaseVersion=X.Y.Z \
  -DdevelopmentVersion=X.Y.Z+1-SNAPSHOT \
  release:prepare
./mvnw -e --no-transfer-progress --batch-mode \
  -DskipTestsDuringRelease \
  -DskipSigning \
  -DstagingRepository=releases::file:///`pwd`/target/artifacts \
  release:stage
----

This will create a staging repository in the parent projects target folder named `artifacts`, which can be deployed to Maven central as follows, given the existence of a valid authentication and GPG passphrase. Take note that the repetition of the release version is required, to avoid checking out the tag created by the release plugin:

[source,bash]
----
export JRELEASER_PROJECT_VERSION=X.Y.Z

export JRELEASER_MAVENCENTRAL_USERNAME=007Schneider
export JRELEASER_MAVENCENTRAL_TOKEN=BonbonAusWurst

export JRELEASER_GPG_PASSPHRASE="Käsebrot ist ein gutes Brot"

./mvnw -e --no-transfer-progress --batch-mode \
  -Dfast \
  -Ddeploy_to_central \
  -pl org.neo4j:neo4j-jdbc-parent \
  jreleaser:deploy
----

Deploying usually takes about 30 minutes, so please be patient.

Doing the GitHub release requires the tag to be checked out and must be run via GitHub actions.
The workflow is configured in link:.github/workflows/release.yml[release.yml] and essentially calls `./mvnw -Dfast --no-transfer-progress package jreleaser:full-release`, which builds the zip distribution and also creates the release notes.


== Tasks

=== Keep the build descriptor (`pom.xml`) sorted

[source,bash]
----
./mvnw sortpom:sort
----

=== Formatting sources / adding headers

When you add new files, you can run

[source,bash]
----
./mvnw license:format
----

to add required headers automatically.

We use https://github.com/spring-io/spring-javaformat[spring-javaformat] to format the source files.

[source,bash]
----
./mvnw spring-javaformat:apply
----

TIP: The Spring Developers write: "The source formatter does not fundamentally change your code. For example, it will not change the order of import statements. It is effectively limited to adding or removing whitespace and line feeds."
     This means the following checkstyle check might still fail.
     Some common errors:
     +
     Static imports, import `javax.*` and `java.*` before others
     +
     Static imports are helpful, yes, but when working with 2 builders in the same project (here jOOQ and Cypher-DSL), they can be quite confusing.

There are plugins for https://github.com/spring-io/spring-javaformat#eclipse[Eclipse] and https://github.com/spring-io/spring-javaformat#intellij-idea[IntelliJ IDEA] and the Checkstyle settings https://github.com/spring-io/spring-javaformat#checkstyle-idea-plugin[can be imported as well].
We took those "as is" and just disabled the lambda check (requiring even single parameters to have parenthesis).

Public classes do require an author tag.
Please add yourself as an `@author` to the `.java` files you added or that modified substantially (more than cosmetic changes).

== Logging

Neo4j-JDBC logs via Java Util Logging (JUL).
A sensible configuration for debugging translated statements could look like this:

[source,properties]
----
handlers=java.util.logging.FileHandler
java.util.logging.FileHandler.level=ALL
java.util.logging.FileHandler.pattern=%h/neo4j-jdbc-%u-%g.log
java.util.logging.FileHandler.formatter=java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format = [%1$tFT%1$tk:%1$tM:%1$tS] %5$s%n

.level=INFO
org.neo4j.jdbc.internal.bolt.internal.NetworkConnection.level=INFO
org.neo4j.jdbc.internal.bolt.BoltMessageExchange.level=OFF
org.neo4j.jdbc.Neo4jStatement.level=FINE
----

This can be used for example with IntelliJs diagnostics.
For that to work, you need to disable class-path isolation in IntelliJ or DataGrip, though.


== Benchkit support

Standalone runner (Java 17 required):

[source,bash]
----
./mvnw -Dfast -am -pl benchkit clean package
TEST_NEO4J_HOST=localhost TEST_NEO4J_PASS=verysecret java -jar benchkit/target/neo4j-jdbc-benchkit-6.0.0-SNAPSHOT.jar
----

Built a Benchkit compliant Docker as follows.

[source,bash]
----
 docker build . -f benchkit/Dockerfile --tag neo4j/neo4j-jdbc-benchkit-backend
 docker run --publish=9000:9000 \
  -e TEST_NEO4J_HOST=host.docker.internal \
  -e TEST_NEO4J_PASS=verysecret neo4j/neo4j-jdbc-benchkit-backend
----

Pick your poison, in both scenarios the following request should work (assuming you have a Neo4j running on your local machine with the given credentials):

[source,bash]
----
curl -X PUT --location "http://localhost:9000/workload" \
    -H "accept: */*" \
    -H "Content-Type: application/json" \
    -d '{
          "method": "executeQuery",
          "database": "",
          "routing": "write",
          "mode": "sequentialSessions",
          "queries": [
            {
              "text": "UNWIND $titles AS title CREATE (n:Movie {title: title}) RETURN n",
              "parameters": {
                "titles": [
                  "Terminator ",
                  "Terminator 2"
                ]
              }
            },
            {
              "text": "UNWIND range(1,10000) AS i CREATE (n:F {i: i}) RETURN n"
            }
          ]
        }'
----

== Conventions

=== Code

Package private by default, no "impl" packages and the like if avoidable.
Public classes must be final unless explicitly designed as SPI.

=== Commits

Please use conventional commits when possible: https://www.conventionalcommits.org/en/v1.0.0/[Conventional Commits].
Two live examples: https://github.com/neo4j-contrib/cypher-dsl[cypher-dsl] and https://github.com/michael-simons/neo4j-migrations[neo4j-migrations].

== Building the documentation

The docs are written with AsciiDoctor inside the `docs` module.
The module is build with Maven.
The `package` goal will process all asciidoc files and bundle them up both as generated site and as an Antora-ready zip archive, ready to be included somewhere else.

[source,bash]
----
./mvnw -Dfast clean package -pl docs -am
----

On JDK21 you can bring up a web-server like this to view the documentation on http://localhost:8000[localhost:8000]

[source,bash]
----
jwebserver -d `pwd`/docs/target/generated-docs/
----

To preview the Antora docs you can run this after the above Maven build succeeds.
The Maven build is necessary so that the version numbers and other references in the source files are processed proper:

[source,bash]
----
npm --prefix etc/antora i
npm --prefix etc/antora run preview
----

The build also provides a zipped version of the Antora module alone, ready to be pushed into another repo under `docs/target/jdbc-manual.zip`.

== Resources

- https://download.oracle.com/otndocs/jcp/jdbc-4_3-mrel3-spec/index.html[JDBC 4.3 Spec]
- https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/java/sql/package-summary.html[Java 17 JDBC API]
- https://docs.oracle.com/javase/tutorial/jdbc/basics/index.html[JDBC Basics] (JDK 8 based, still useful though)
