= Neo4j JDBC Driver
Michael Simons <michael.simons@neo4j.com>
:doctype: article
:lang: en
:listing-caption: Listing
:source-highlighter: coderay
:icons: font
// tag::properties[]
:groupId: org.neo4j
:artifactIdCore: neo4j-jdbc
:latest_version: 6.2.1
:branch: main
// end::properties[]
:examplesdir: docs/src/main/asciidoc/modules/ROOT/examples

[abstract]
--
// tag::abstract[]
This is the manual for the official Neo4j JDBC Driver.

This driver is officially supported and endorsed by Neo4j.
It is a standalone driver, independent of and *not* built on top of the https://github.com/neo4j/neo4j-java-driver[common Neo4j Java Driver].
While the latter provides a Neo4j-idiomatic way to access Neo4j from Java, the JDBC driver adheres to https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/java/sql/package-summary.html[JDBC 4.3].

NOTE: This documentation refers to *this* driver as the _Neo4j JDBC Driver_ and to the idiomatic Neo4j driver as the _common Neo4j Java Driver_.
// end::abstract[]
--

image:https://github.com/neo4j/neo4j-jdbc/workflows/build/badge.svg[link=https://github.com/neo4j/neo4j-jdbc/actions]
image:https://sonar.neo4j.ninja/api/project_badges/measure?project=neo4j-jdbc&token=sqb_6d14b417b6cd8c19820429dde7fd0dd34f0f5302&metric=coverage[link=https://sonar.neo4j.ninja/dashboard?id=neo4j-jdbc]
image:https://sonar.neo4j.ninja/api/project_badges/measure?project=neo4j-jdbc&token=sqb_6d14b417b6cd8c19820429dde7fd0dd34f0f5302&metric=alert_status[link=https://sonar.neo4j.ninja/dashboard?id=neo4j-jdbc]

== Download

=== Include in a Maven build

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>{groupId}</groupId>
    <artifactId>{artifactIdCore}-full-bundle</artifactId>
    <version>{latest_version}</version>
</dependency>
----

=== Include in a Gradle build

[source,groovy,subs="verbatim,attributes"]
----
dependencies {
    implementation '{groupId}:{artifactIdCore}-full-bundle:{latest_version}'
}
----

All https://github.com/neo4j/neo4j-jdbc/releases/[releases] from 6.0 onwards contain a zipped version of the driver, including a PDF version of the manual.
We offer several distributions, please have a look http://neo4j.github.io/neo4j-jdbc/{latest_version}/#_distribution[here] for more details.
If you feel adventurous, grab the code and build the driver yourself.
You find the instructions in our link:CONTRIBUTING.adoc[contribution documentation].

== Quickstart

After adding the bundle to your application, you can use the Neo4j JDBC driver as any other JDBC driver.

// tag::quickstart[]
TIP: In case any tooling asks you for the name of the concrete driver class, it is `org.neo4j.jdbc.Neo4jDriver`.

[source, java, tabsize=4]
.Acquire a connection and execute a query
----
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.List;

public final class Quickstart {

    static void queryWithCypher() {
        var query = """
                MATCH (m:Movie)<-[:ACTED_IN]-(p:Person)
                RETURN m.title AS title, collect(p.name) AS actors
                ORDER BY m.title
                """;

        var url = "jdbc:neo4j://localhost:7687";
        var username = "neo4j";
        var password = "verysecret";

        try (var con = DriverManager.getConnection(url, username, password); // <.>
                var stmt = con.createStatement();  // <.>
                var result = stmt.executeQuery(query)) { // <.>

            while (result.next()) { // <.>
                var movie = result.getString(1); // <.>
                var actors = (List<String>) result.getObject("actors"); // <.>
                System.out.printf("%s%n", movie);
                actors.forEach(actor -> System.out.printf("\t * %s%n", actor));
            }
        }
        catch (SQLException ex) {
            throw new RuntimeException(ex);
        }
    }
}
----
<.> Instantiate a JDBC connection. There's no need to do any class loading beforehand, the driver will be automatically registered
<.> Create a (reusable) statement
<.> Execute a query
<.> Iterate over the results, as with any other JDBC result set
<.> JDBC's indexing starts at 1
<.> JDBC also allows retrieval of result columns by name; the Neo4j JDBC driver also supports complex objects, such as lists

In the example above we used Neo4j's _lingua franca_, https://neo4j.com/docs/getting-started/cypher-intro/[Cypher], to query the database.
The Neo4j JDBC Driver has limited support for using SQL as well.
It can do so automatically or on a case-by-case basis.
To translate a single, call `java.sql.Connection#nativeSQL(String)` and use the result in your queries.
For automatic translation, instantiate the driver setting the optional URL parameter `sql2cypher` to `true`.
The following example shows how:

[source, java, tabsize=4, indent=0]
.Configure the JDBC driver to automatically translate SQL to cypher.
----
var query = """
        SELECT m.title AS title, collect(p.name) AS actors
        FROM Person as p
        JOIN Movie as m ON (m.id = p.ACTED_IN)
        ORDER BY m.title
        """; // <.>

var url = "jdbc:neo4j://localhost:7687?enableSQLTranslation=true";

try (var con = DriverManager.getConnection(url, username, password);
        var stmt = con.createStatement();
        var result = stmt.executeQuery(query)) {

    while (result.next()) {
        var movie = result.getString(1);
        var actors = (List<String>) result.getObject("actors");
        System.out.printf("%s%n", movie);
        actors.forEach(actor -> System.out.printf("\t * %s%n", actor));
    }
}
----
<.> This SQL query will be translated into the same Cypher query of the previous example.
The remainder of the method is identical to before.

// end::quickstart[]

For more information, see http://neo4j.github.io/neo4j-jdbc/main/#s2c_introduction[SQL to Cypher translation].

== Introduction
// tag::introduction[]
JDBC stands for "Java Database Connectivity" and is thus not bound exclusively to relational databases.
Nevertheless, JDBC's terms, definitions, and behavior are highly influenced by SQL and relational databases.
As Neo4j is a graph database with quite a different paradigm than relational and a non-standardized behaviour in some areas, there might be some details that don't map 100% in each place, and we make sure to educate you about these in this documentation.

This documentation focuses on install, use, and configure the Neo4j JDBC Driver, as well as discussing the driver's design choices.
While we do provide runnable examples showing how to use JDBC with Neo4j, this is not a documentation about how to correctly use JDBC as an API.

NOTE: The Neo4j JDBC Driver requires JDK 17 on the client side and Neo4j 5.5+ on the server side.
To use it with a Neo4j cluster, server-side routing must be enabled on the cluster.

=== Features

* Fully supports the Java module system
* Adheres to JDBC 4.3
* Can run any Cypher statement
* Implements `DatabaseMetaData` and `ResultSetMetaData` as fully as possible with a nearly schemaless database and general very flexible result sets, allowing for automatic metadata retrieval from ETL and ELT tools
* Provides an https://en.wikipedia.org/wiki/Service_provider_interface[SPI] to hook in translators from SQL to Cypher
* Provides an optional default implementation to translate many SQL statements into semantically similar Cypher statements
* Can be safely used with JDBC connection pools as opposed to the common Neo4j Java Driver or any JDBC driver based on that, as it doesn't do internal connection pooling and transaction management otherwise than dictated by the JDBC Spec

The absence of any connection pooling and transaction management is an advantage of the Neo4j JDBC Driver over the common Neo4j Java Driver.
It allows to pick and choose any database connection pooling system such as https://github.com/brettwooldridge/HikariCP[HikariCP] and transaction management such as https://jakarta.ee/specifications/transactions/[Jakarta Transactions].

=== Limitations

* The database metadata is retrieved using Neo4j's schema methods, such as `db.labels`, `db.schema.nodeTypeProperties()`, which may not always be accurate
* While single label nodes map naturally to table names, nodes with multiple labels don't
* There is no reliable way to always determine the datatype for properties on nodes, as it would require reading all of them (which this driver does not do)
* Some JDBC features are not supported yet (such as the `CallableStatement`); some feature will never be supported
* The SQL to Cypher translator supports only a limited subset of clauses and SQL constructs that can be equivalently translated to Cypher (See xref:sql2cypher.adoc#s2c_supported_statements[Supported statements])
* There is no "right" way to map `JOIN` statements to relationships, so your mileage may vary

=== When to use the Neo4j JDBC Driver?

* Integration with ETL and ELT tools that don't offer an integration based on the common Neo4j Java driver
* An easier on-ramp towards Neo4j for people familiar with JDBC, who want to keep using that API, but with Cypher and Neo4j
* Integration for ecosystems like Jakarta EE whose transaction management directly supports any JDBC-compliant driver
* Integration with database migration tools such as Flyway

*There is no need to redesign an application that is built on the common Neo4j Java Driver to migrate to this driver.*
If your ecosystem already provides a higher-level integration based on the common Neo4j Java Driver, such as https://github.com/spring-projects/spring-data-neo4j[Spring Data Neo4j (SDN)] for https://spring.io/projects/spring-boot/[Spring], there is no need to switch to something else.
In case of https://quarkus.io[Quarkus], the Neo4j JDBC Driver is an option to consider: although we do provide an integration for the https://github.com/quarkiverse/quarkus-neo4j[common Neo4j Java Driver], this integration does not support Quarkus' transaction systems in contrast to this driver.

As there is little incentive to use this driver with Hibernate (https://github.com/neo4j/neo4j-ogm[Neo4j-OGM] or SDN are the best alternatives for Neo4j), it might be worth giving https://spring.io/projects/spring-data-jdbc/[Spring Data JDBC] a try.

=== Differences with the previous versions of this driver and other JDBC drivers for Neo4j

Several other JDBC drivers exists for Neo4j, most notably the previous versions 4 and 5 of this driver.
Most (if not all) of them wrap the common Neo4j Java Driver and implement the JDBC spec on top of that.
This comes with a number of issues:

* You end up with a _pool of connection pools_, because the common Neo4j Java Driver manages a connection pool, whereas JDBC drivers delegate this task to dedicated pooling solutions.
* The transaction management of the common Neo4j Java Driver is not aligned with the way JDBC manages transactions.
* Older versions of the Neo4j JDBC driver shade a few dependencies, such as `Jackson` as well as additional logging frameworks.
This takes a toll on the classpath and, in case of logging, it leads to runtime problems.
* Existing drivers with an SQL-to-Cypher translation layer are "read-only" and don't support write statements, so they cannot be used for ETL use-cases aiming to ingest data into Neo4j.

WARNING: This driver does not support automatic reshaping or flattening of the result sets, as the previous versions do.
If you query for nodes, relationships, paths, or maps, you should use `getObject` on the result sets and cast them to the appropriate type (you find all of them inside the package `org.neo4j.jdbc.values`).
However, the default SQL-to-Cypher translator will (when connected to a database) figure out what properties nodes have and turn the asterisk (`*`) into individual columns of nodes and relationships, just like what you would expect when running a `SELECT *` statement.

// end::introduction[]

For information on upgrade/migration from other drivers to this one, see http://neo4j.github.io/neo4j-jdbc/main/#_migrating_from_older_versions_or_other_jdbc_drivers_for_neo4j[Migrating from older versions or other JDBC drivers for Neo4j].
