== Neo4j JDBC Driver image:https://travis-ci.org/larusba/neo4j-jdbc.svg?branch=master["Build Status", link="https://travis-ci.org/larusba/neo4j-jdbc"] ==

This is the Neo4j JDBC driver supporting various types of database connections.
By using this driver you will be able to interact with a Neo4J database also using the new BOLT protocol.

Because Neo4J is a graph database it's not serving data in the relational way and the exact purpose of this project is to allow
projects using the classic JDBC connector in the relational paradigm to interact with Neo4J.

*Note*: this project is an alpha-level and is currently in development so the API will not be stable. Please try it out and give us
feedback and suggestions but don't use this in a production environment (right now).


The driver can be used with:

* every kind of Neo4J server exposing services through the BOLT protocol

The driver will be implemented also for:

* HTTP connection

* direct file connection


This project is made by the following modules:

* https://github.com/larusba/neo4j-jdbc/tree/master/neo4j-jdbc-bolt[Neo4j JDBC - Bolt] - the module supporting the bolt protocol

* https://github.com/larusba/neo4j-jdbc/tree/master/neo4j-jdbc[Neo4j JDBC] - the core module

=== Minimum viable snippet ===

---------------------------------------------
// Make sure Neo4j Driver is registered
Class.forName("it.neo4j.jdbc.bolt.BoltDriver");

// Connect
Connection con = DriverManager.getConnection("jdbc:bolt://localhost");

// Querying
try (Statement stmt = con.createStatement()) {
    ResultSet rs = stmt.executeQuery("MATCH (n:User) RETURN n.name");
	while (rs.next()) {
		System.out.println(rs.getString("n.name"));
	}
}
con.close();
---------------------------------------------

=== Usage ===

* Add the JDBC driver jar file to your project

* Load the driver using the class "it.neo4j.jdbc.bolt.BoltDriver" for BOLT protocol

* Execute queries using the Cyper graph query language

===== Server =====

* Install a Neo4j 3.0 server and start it with the BOLT protocol enabled

* Connect with URLs on the form jdbc:bolt://<host>:<port>/, e.g. jdbc:bolt://localhost/

=== Currently in development (Bolt module) ===

* Connection [IN PROGRESS]

* Statement [IN PROGRESS]

* Driver [IN PROGRESS]

* ResultSet [IN PROGRESS]

* Transactions [TODO]

* Metadata [TODO]

* Prepared Statements [TODO]

* Parameters [TODO]

=== Thank you ===

We'd also like to thank for their precious support:

* https://twitter.com/darthvader42[Stefan Armbruster], NEO TECHNOLOGY - Presales Engineer for EMEA

* https://twitter.com/mesirii[Michael Hunger], NEO TECHNOLOGY - Head of Developer Relations, Caretaker Neo4j Community

=== License ===

Copyright (c) 2016 http://www.larus-ba.it[LARUS Business Automation]

This file is part of the "LARUS Integration Framework for Neo4j".

The "LARUS Integration Framework for Neo4j" is licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

See the License for the specific language governing permissions and
limitations under the License.
