== Overview: Neo4j JDBC Driver
:neo4j-jdbc-version: 3.3.1

ifndef::env-docs[]
image:https://travis-ci.org/neo4j-contrib/neo4j-jdbc.svg?branch=master["Build Status", link="https://travis-ci.org/neo4j-contrib/neo4j-jdbc"]

You can find the full documentation at: http://neo4j-contrib.github.io/neo4j-jdbc/
endif::env-docs[]

*This is the official JDBC driver for Neo4j*.

This driver was mainly developed by http://larus-ba.it[Larus BA, Italy], a certified consulting and integration solutions partner for Neo4j.
*Thank you* so much for all your work.

Being a graph database, Neo4j is not serving data in a relational way, nevertheless thanks to this driver it's possible for
projects that are using the classic JDBC connector in the relational paradigm to interact with Neo4j.

This driver supports various types of database transports, through:

* The `Bolt` protocol using `jdbc:neo4j:bolt://<host>:<port>/` from Neo4j 3.0+
* The `Bolt+Routing` protocol using `jdbc:neo4j:bolt+routing://<host>:<port>/` from Neo4j 3.1+
* The `HTTP` protocol using `jdbc:neo4j:http://<host>:<port>/` from Neo4j 2.0+

Going forward there will also be support for:

* direct file connection
* embedded connection

[NOTE]
The previous JDBC driver for Neo4j 2.x was moved to the https://github.com/neo4j-contrib/neo4j-jdbc-2x repository.



.Versions compatibility
|===
|Neo4j-JDBC | Neo4j version | Neo4j Driver | Java | Protocols | Temporal and Spatial

|https://github.com/neo4j-contrib/neo4j-jdbc/releases/tag/3.0.3[3.0.3]
|\<= 3.0.x
|1.3.0
|1.7
|http, bolt
|no

|https://github.com/neo4j-contrib/neo4j-jdbc/releases/tag/3.1.0[3.1.0]
|\<= 3.1.x
|1.3.0
|1.7
|http, bolt
|no

|https://github.com/neo4j-contrib/neo4j-jdbc/releases/tag/3.3.0[3.3.0]
|\<= 3.3.0
|1.4.6
|1.7
|http, bolt
|no

|https://github.com/neo4j-contrib/neo4j-jdbc/releases/tag/3.3.1[3.3.1]
|\<= 3.3.x
|1.4.6
|1.7
|http, bolt, bolt+routing
|no

|3.4.0
|\<= 3.4.x
|1.6.1
|1.8
|http, bolt, bolt+routing
|yes
|===


=== Maven dependency

For the all-in-one module supporting both Bolt and HTTP, you can simply use:

[source,xml]
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-jdbc-driver</artifactId>
    <version>{neo4j-jdbc-version}</version>
</dependency>

If you want only one of the protocols, you can depend on its module:

[source,xml]
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-jdbc-bolt</artifactId>
    <version>{neo4j-jdbc-version}</version>
</dependency>

or

[source,xml]
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-jdbc-http</artifactId>
    <version>{neo4j-jdbc-version}</version>
</dependency>

=== Minimum viable snippet

// tag::mvs[]

.Dependency declaration
[source,subs=attributes]
-----
org.neo4j:neo4j-jdbc-driver:{neo4j-jdbc-version}
-----

.Run Query
[source,java]
----
// Connecting
try (Connection con = DriverManager.getConnection("jdbc:neo4j:bolt://localhost", 'neo4j', password)) {

    // Querying
    String query = "MATCH (u:User)-[:FRIEND]-(f:User) WHERE u.name = {1} RETURN f.name, f.age";
    try (PreparedStatement stmt = con.prepareStatement(query)) {
        stmt.setString(1,"John");

        try (ResultSet rs = stmt.executeQuery()) {
            while (rs.next()) {
                System.out.println("Friend: "+rs.getString("f.name")+" is "+rs.getInt("f.age"));
            }
        }
    }
}
----
// end::mvs[]

*Please note* that the example above uses the try-with-resource blocks that automatically closes resources when the `try` block is exited.

=== Usage with Neo4j Server

* Install a Neo4j 3.3.x server and start it with the Bolt protocol enabled
* Connect with URLs in the following 3 forms:
** `jdbc:neo4j:http://<host>:<port>/` (e.g. `jdbc:neo4j:http://localhost/`)
** `jdbc:neo4j:bolt://<host>:<port>/` (e.g. `jdbc:neo4j:bolt://localhost/`)
** `jdbc:neo4j:bolt+routing://<host>:<port>/` (e.g. `jdbc:neo4j:bolt+routing://localhost?routing:policy=eu`)
* You can also use additional parameters in the URL separated by an `&` character for authentication, debug mode, SSL encryption and flattening e.g. `jdbc:neo4j:bolt://localhost/?user=neo4j&password=xxxx&debug=true&nossl&flatten=[-1,100,1000]`

[NOTE]
*We've deprecated the usage of `,` as the parameter separator in favour of `&` to be compliant with the URL parameter syntax.*

* Add the JDBC driver dependency or jar file to your project
* Get a connection from `DriverManager`
* Execute queries and transactions using the Cypher graph query language

=== Flattening

As most JDBC clients and tools don't support complex objects, the driver can flatten returned nodes and relationships by providing all their properties as individual columns with names like `u.name`,`r.since` if you just return a node `u` or relationship `r`.

This is enabled with the JDBC-URL parameter `flatten=<rows>`, where `<rows>` indicates how many rows are sampled to determine those columns.
With `-1` all rows are sampled and with any other value you determine the number of rows being looked at.

=== Building the driver yourself

First clone https://github.com/neo4j-contrib/neo4j-jdbc[the repository].

This project is composed by the following modules:

* https://github.com/neo4j-contrib/neo4j-jdbc/tree/master/neo4j-jdbc[Neo4j JDBC] - the core module
* https://github.com/neo4j-contrib/neo4j-jdbc/tree/master/neo4j-jdbc-bolt[Neo4j JDBC - Bolt] - module supporting the Bolt protocol
* https://github.com/neo4j-contrib/neo4j-jdbc/tree/master/neo4j-jdbc-http[Neo4j JDBC - HTTP] - module supporting the HTTP protocol
* https://github.com/neo4j-contrib/neo4j-jdbc/tree/master/neo4j-jdbc-driver[Neo4j JDBC - Driver packaging] - module to package all above modules


.Run all unit tests & integration tests
-------------------------------------------------
mvn clean test
-------------------------------------------------

.Run only integration tests
-------------------------------------------------
mvn clean test -Pintegration-test
-------------------------------------------------

.Run performance tests
--------------------------------------------------
mvn clean test -Pperformance-test
--------------------------------------------------

[NOTE]
To run the performance test, you must have a Neo4j Server 3.3.x running with the Bolt protocol enabled on port 7687 (default).


=== License

Copyright (c) 2017 http://neo4j.com[Neo4j] and http://www.larus-ba.it[LARUS Business Automation]

The "Neo4j JDBC Driver" is licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.

You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

See the License for the specific language governing permissions and
limitations under the License.

=== Feedback

Please provide feedback and report bugs as link:./issues[GitHub issues] or join the http://neo4j.com/slack[neo4j-users Slack] and ask on the #neo4j-jdbc channel.
You might also ask on http://stackoverflow.com/questions/tagged/neo4j+jdbc[StackOverflow], please tag your question there with `neo4j` and `jdbc`.
