== Neo4j JDBC Driver image:https://travis-ci.org/larusba/neo4j-jdbc.svg?branch=master["Build Status", link="https://travis-ci.org/larusba/neo4j-jdbc"] ==

This is the Neo4j JDBC driver that supports various types of database connections.
With this driver you will be able to interact with a Neo4J database using also the new BOLT protocol.

Being a graph database, Neo4J it's not serving data in a relational way and the exact purpose of this project is to allow
projects that are using the classic JDBC connector in the relational paradigm to interact with Neo4J.

*Note*: this project is at an alpha-level stage and is currently in development so the APIs will not be stable. Please try it out and give us
feedback and suggestions but don't use it in a production environment (yet).


The driver can be used with:

* every kind of Neo4J server exposing services through the BOLT protocol (3.0+)

The driver will be implemented also for:

* HTTP connection

* direct file connection

* embedded connection


This project is composed by the following modules:

* https://github.com/larusba/neo4j-jdbc/tree/master/neo4j-jdbc-bolt[Neo4j JDBC - Bolt] - module supporting the bolt protocol

* https://github.com/larusba/neo4j-jdbc/tree/master/neo4j-jdbc[Neo4j JDBC] - the core module

=== Minimum viable snippet ===

---------------------------------------------
// Make sure Neo4j Driver is registered
Class.forName("it.larusba.neo4j.jdbc.Driver");

// Connect
Connection con = DriverManager.getConnection("jdbc:bolt://localhost");

// Querying
try (Statement stmt = con.createStatement()) {
    ResultSet rs = stmt.executeQuery("MATCH (n:User) RETURN n.name");
	while (rs.next()) {
		System.out.println(rs.getString("n.name"));
	}
}
con.close();
---------------------------------------------

=== Usage ===

* Add the JDBC driver jar file to your project

* Load the driver using the class "BoltDriver" for BOLT protocol

* Execute queries using the Cyper graph query language

=== Tests usage ===

* Run all unitary tests:
-------------------------------------------------
mvn clean test
-------------------------------------------------

* Run integration tests:
-------------------------------------------------
mvn clean -fneo4j-jdbc-bolt/pom.xml -Dtest=*IT test
-------------------------------------------------

* Run performance tests:

--------------------------------------------------
mvn clean -fneo4j-jdbc-bolt/pom.xml -Dtest=*PT test
--------------------------------------------------

WARNING: Must have a neo4j (M05) stand alone with Bolt protocol on port 7687 (default)

===== Server =====

* Install a Neo4j 3.0 server and start it with the BOLT protocol enabled

* Connect with URLs in the form jdbc:bolt://<host>:<port>/ e.g. jdbc:bolt://localhost/

* You can also set comma separated parameters in the URL for authentication and debug mode, e.g. jdbc:bolt://localhost/?user=neo4j,password=neo4j,debug=true

=== Release 3.0 Schedule ===

Milestone 01 [RELEASED]

* Basic snippet working

* Logging

* Performance tests

* M04 of Neo4j and Bolt driver

* Transactions working (both manual and autocommit)

* executeQuery + executeUpdate working

* ResultSet getters managing nodes and relationships

Milestone 02 [2016-04-10]

* ResultSet getters managing paths [TODO]

* Prepared statements [DONE]

* M05 of Neo4j [DONE]

* RC1 Neo4j bolt driver [DONE]

* Authentication [DONE]

* Pentaho support [TODO]

* Flattening of results [DONE]

Milestone 03 [2016-04-20]

* Batching [TODO]

=== Thank you ===

We'd also like to thank for their precious support:

* https://twitter.com/darthvader42[Stefan Armbruster], NEO TECHNOLOGY - Presales Engineer for EMEA

* https://twitter.com/mesirii[Michael Hunger], NEO TECHNOLOGY - Head of Developer Relations, Caretaker Neo4j Community

=== License ===

Copyright (c) 2016 http://www.larus-ba.it[LARUS Business Automation]

This file is part of the "LARUS Integration Framework for Neo4j".

The "LARUS Integration Framework for Neo4j" is licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

See the License for the specific language governing permissions and
limitations under the License.
