== Overview: Neo4j JDBC Driver
:neo4j-jdbc-version: 5.0.0

image::https://github.com/neo4j-contrib/neo4j-jdbc/workflows/CI/badge.svg?branch=5.0[CI]

ifndef::env-docs[]

You can find the full documentation at: http://neo4j-contrib.github.io/neo4j-jdbc/
endif::env-docs[]

*This is a JDBC driver for Neo4j supporting Cypher over JDBC*.

This driver was mainly developed by http://larus-ba.it[Larus BA, Italy], a certified consulting and integration solutions partner for Neo4j.
*Thank you* so much for all your work.

Being a graph database, Neo4j is not serving data in a relational way, nevertheless thanks to this driver it's possible for
projects that are using the classic JDBC connector in the relational paradigm to interact with Neo4j.

=== Download

Simply add the JDBC dependency to your project:

[source,xml]
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-jdbc-bolt</artifactId>
    <version>{neo4j-jdbc-version}</version>
    <scope>runtime</scope>
</dependency>


=== Transport support
From 5.0 onwards, this driver supports only the Bolt protocol, through:

* The `Bolt` direct connection protocol using `jdbc:neo4j:bolt://<host>:<port>/`
* The `Bolt` routing-aware protocol for clusters using `jdbc:neo4j:neo4j://<host>:<port>/`

You can also specify the encryption via the Bolt URI scheme:

 - `jdbc:neo4j:bolt://<host>:<port>/`
 - `jdbc:neo4j:bolt+s://<host>:<port>/`
 - `jdbc:neo4j:bolt+ssc://<host>:<port>/`
 - `jdbc:neo4j:neo4j://<host>:<port>/`
 - `jdbc:neo4j:neo4j+s://<host>:<port>/`
 - `jdbc:neo4j:neo4j+ssc://<host>:<port>/`

See the official https://neo4j.com/docs/java-manual/current/client-applications/#java-driver-connection-uris[Neo4j Java driver documentation] to learn more.

=== Minimum viable snippet

// tag::mvs[]

.Dependency declaration
[source,subs=attributes]
-----
org.neo4j:neo4j-jdbc-bolt:{neo4j-jdbc-version}
-----

.Run Query
[source,java]
----
// Connecting
try (Connection connection = DriverManager.getConnection("jdbc:neo4j:bolt://localhost", "neo4j", password);
    // Querying
     PreparedStatement stmt = connection.prepareStatement("MATCH (u:User)-[:FRIEND]-(f:User) WHERE u.name = $0 RETURN f.name, f.age")) {
     
    stmt.setString(0, "John");
    
    try (ResultSet rs = stmt.executeQuery()) {
        while (rs.next()) {
            System.out.println("Friend: "+rs.getString("f.name")+" is "+rs.getInt("f.age"));
        }
    }
}
----
// end::mvs[]


=== Configuration

|===
|Property Name |Supported Values |Description

|trust.strategy |TRUST_ALL_CERTIFICATES, TRUST_CUSTOM_CA_SIGNED_CERTIFICATES, TRUST_SYSTEM_CA_SIGNED_CERTIFICATES |The supported trusted strategies
|trusted.certificate.file |File Path |The path of the certificate file
|connection.acquisition.timeout |Any Long |The acquisition time
|connection.liveness.check.timeout |Any Long |The liveness check timeout
|connection.timeout |Any Long |The connection timeout
|encryption |true/false |Activate the application encryption
|leaked.sessions.logging |true/false |If log leaked session
|max.connection.lifetime |Any Long |The connection lifetime
|max.connection.poolsize |Any Int |The max pool size
|max.transaction.retry.time |Any Long | The retry time for a transaction transient error
|database |String |The database name, if not specified connects to the default instance
|readonly |true/false |If specified creates a fixed read only connection, any further modification via the `Connection#setReadOnly` method will have no effect
|autocommit |true/false |If specified sets the autocommit property as initial value, you can still change the autocommit value by using `Connection#setAutoCommit` method, but it will have effect only for newly created transactions
|usebookmarks |true/false |If specified disables the bookmarks
|===


=== Flattening

As most JDBC clients and tools don't support complex objects, the driver can flatten returned nodes and relationships by providing all their properties as individual columns with names like `u.name`,`r.since` if you just return a node `u` or relationship `r`.

This is enabled with the JDBC-URL parameter `flatten=<rows>`, where `<rows>` indicates how many rows are sampled to determine those columns.
With `-1` all rows are sampled and with any other value you determine the number of rows being looked at.

=== Tomcat
When the JDBC driver is configured as a JNDI resource into Tomcat, you must include these two arguments on `Resource` configuration:

* `removeAbandonedOnBorrow="true"`
* `closeMethod="close"`

Here's an example:

[source,xml]
----
    <Resource name="jdbc/neo4j"
              auth="Container"
              type="javax.sql.DataSource"
              username="neo4j"
              password="password"
              driverClassName="org.neo4j.jdbc.bolt.BoltDriver"
              url="jdbc:neo4j:bolt://localhost"
              removeAbandonedOnBorrow="true"
              closeMethod="close"
              />
----

=== Building the driver yourself

First clone https://github.com/neo4j-contrib/neo4j-jdbc[the repository].

This project is composed by the following modules:

* https://github.com/neo4j-contrib/neo4j-jdbc/tree/5.0/neo4j-jdbc[Neo4j JDBC] - the core module
* https://github.com/neo4j-contrib/neo4j-jdbc/tree/5.0/neo4j-jdbc-bolt[Neo4j JDBC - Bolt] - module supporting the Bolt protocol

.Run all unit tests & integration tests
-------------------------------------------------
mvn clean test
-------------------------------------------------

.Run only integration tests
-------------------------------------------------
mvn clean test -Pintegration-test
-------------------------------------------------

.Run performance tests
--------------------------------------------------
mvn clean test -Pperformance-test
--------------------------------------------------

[NOTE]
To run the performance test, you must have a Neo4j Server running with the Bolt protocol enabled on port 7687 (default).


=== License

Copyright (c) https://neo4j.com[Neo4j] and https://www.larus-ba.it[LARUS Business Automation]

The "Neo4j JDBC Driver" is licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.

You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

See the License for the specific language governing permissions and
limitations under the License.

=== Feedback

Please provide feedback and report bugs as link:./issues[GitHub issues] or join the http://neo4j.com/slack[neo4j-users Slack] and ask on the #neo4j-jdbc channel.
You might also ask on http://stackoverflow.com/questions/tagged/neo4j+jdbc[StackOverflow], please tag your question there with `neo4j` and `jdbc`.
