== Neo4j JDBC Driver ==

This is the Neo4j JDBC driver supporting various types of database connections.
By using this driver you will be able to interact with a Neo4J database also using the new BOLT protocol.

Because Neo4J is a graph database it's not serving data in the relational way and the exact purpose of this project is to allow
projects using the classic JDBC connector in the relational paradigm to interact with Neo4J.

*Note*: this project is an alpha-level and is currently in development so the API will not be stable. Please try it out and give us
feedback and suggestions but don't use this in a production environment (right now).


The driver can be used with:

* every kind of Neo4J server exposing services through the BOLT protocol

The driver will be implemented also for:

* HTTP connection

* direct file connection


This project is made by the following modules:

* https://github.com/larusba/neo4j-jdbc/tree/master/neo4j-jdbc-bolt[Neo4j JDBC - Bolt] - the module supporting the bolt protocol

* https://github.com/larusba/neo4j-jdbc/tree/master/neo4j-jdbc[Neo4j JDBC] - the core module

=== Minimum viable snippet ===

---------------------------------------------
// Make sure Neo4j Driver is registered
Class.forName("it.neo4j.jdbc.bolt.BoltDriver");

// Connect
Connection con = DriverManager.getConnection("jdbc:bolt://localhost:7474");

// Querying
try (Statement stmt = con.createStatement()) {
    ResultSet rs = stmt.executeQuery("MATCH (n:User) RETURN n.name");
	while (rs.next()) {
		System.out.println(rs.getString("n.name"));
	}
}
---------------------------------------------

=== Usage ===

* Add the JDBC driver jar file to your project

* Load the driver using the class "it.neo4j.jdbc.bolt.BoltDriver" for BOLT protocol

* Execute queries using the Cyper graph query language

===== Server =====

* Install a Neo4j 3.0 server and start it with the BOLT protocol enabled

* Connect with URLs on the form jdbc:bolt://<host>:<port>/, e.g. jdbc:bolt://localhost:7474/