== Neo4j JDBC Driver image:https://travis-ci.org/larusba/neo4j-jdbc.svg?branch=master["Build Status", link="https://travis-ci.org/larusba/neo4j-jdbc"] ==

This is the Neo4j JDBC driver that supports various types of database connections.
With this driver you will be able to interact with a Neo4J database using also the new BOLT protocol.

Being a graph database, Neo4J is not serving data in a relational way and the exact purpose of this project is to allow
projects that are using the classic JDBC connector in the relational paradigm to interact with Neo4J.


The driver can be used with:

* every kind of Neo4J server exposing services through the BOLT protocol (3.0.X)

The driver will be implemented also for:

* direct file connection
* embedded connection


This project is composed by the following modules:

* https://github.com/larusba/neo4j-jdbc/tree/master/neo4j-jdbc[Neo4j JDBC] - the core module
* https://github.com/larusba/neo4j-jdbc/tree/master/neo4j-jdbc-driver[Neo4j JDBC - Driver packaging] - module to package all above modules
* https://github.com/larusba/neo4j-jdbc/tree/master/neo4j-jdbc-bolt[Neo4j JDBC - Bolt] - module supporting the bolt protocol
* https://github.com/larusba/neo4j-jdbc/tree/master/neo4j-jdbc-http[Neo4j JDBC - Http] - module supporting the http protocol


=== Minimum viable snippet ===

---------------------------------------------
// Connect
Connection con = DriverManager.getConnection("jdbc:bolt://localhost");

// Querying
try (Statement stmt = con.createStatement()) {
    ResultSet rs = stmt.executeQuery("MATCH (n:User) RETURN n.name");
	while (rs.next()) {
		System.out.println(rs.getString("n.name"));
	}
}
con.close();
---------------------------------------------

=== Usage ===

* Add the JDBC driver jar file to your project

* Load the driver using the class "BoltDriver" for BOLT protocol

* Execute queries using the Cyper graph query language

=== Tests usage ===

* Run all unitary tests:
-------------------------------------------------
mvn clean test
-------------------------------------------------

* Run integration tests:
-------------------------------------------------
mvn clean test -Pintegration-test
-------------------------------------------------

* Run performance tests:

--------------------------------------------------
mvn clean test -Pperformance-test
--------------------------------------------------

WARNING: Must have a neo4j (3.0.X) stand alone with Bolt protocol on port 7687 (default)

===== Server =====

* Install a Neo4j 3.0.X server and start it with the BOLT protocol enabled

* Connect with URLs in the form jdbc:bolt://<host>:<port>/ e.g. jdbc:bolt://localhost/

* You can also set comma separated parameters in the URL for authentication, debug mode and ssl encryption, e.g. jdbc:bolt://localhost/?user=neo4j,password=neo4j,debug=true,noSsl

=== Release 3.0 Schedule ===

Milestone 01 [RELEASED]

* Basic snippet working

* Logging

* Performance tests

* M04 of Neo4j and Bolt driver

* Transactions working (both manual and autocommit)

* executeQuery + executeUpdate working

* ResultSet getters managing nodes and relationships

Milestone 02 [RELEASED]

* ResultSet getters managing paths

* Prepared statements

* RC1 of Neo4j

* RC2 Neo4j bolt driver

* Authentication

* Pentaho basic support

* Flattening of results

* JSON string for nodes, relationships and paths

Milestone 03 [RELEASED]

* Batch processing

* Bug fix

* Neo4j Java Driver 1.0.1

* Neo4j 3.0.1

=== Thank you ===

We'd also like to thank for their precious support:

* https://twitter.com/darthvader42[Stefan Armbruster], NEO TECHNOLOGY - Presales Engineer for EMEA

* https://twitter.com/mesirii[Michael Hunger], NEO TECHNOLOGY - Head of Developer Relations, Caretaker Neo4j Community

* https://twitter.com/logisima[Benoît Simard], NEO TECHNOLOGY - Technical Consultant at Neo Technology

=== License ===

Copyright (c) 2016 http://www.larus-ba.it[LARUS Business Automation]

This file is part of the "LARUS Integration Framework for Neo4j".

The "LARUS Integration Framework for Neo4j" is licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

See the License for the specific language governing permissions and
limitations under the License.
