= Neo4j JDBC Driver - Bolt

This module implements the neo4j-jdbc driver with the BOLT protocol.

This module is a JDBC-way wrapper of the https://github.com/neo4j/neo4j-java-driver[Neo4j-java] driver currently implementing an alpha
version of the BOLT protocol for Java.

== Special wrapping for neo4j nodes relationships and paths. ==

Even if you can access each value in a `ResultSet` with multiple type-specific method, you might want to get a whole _node_, _relationship_ or _path_.

This *can't* be done by default with JDBC standard methods, to allow this usage we re-invented the use of `getObject(*)` method.

If the object you are trying to get is an `*instanceof* InternalNode` (thus being a neo4j Node) it will be returned wrapped in a `Map<String, Object>`. This map will contain all the object's properties where their names (`String`) are the keys. It will also contains two default values mapped as "`_id`", representing neo4j internal identity ID and "`_labels`", a `Collection` of all the labels of that node.

If the object is instead an `*instanceof* InternalRelationship` (thus being a neo4j Relationship) it will be also returned as a `Map<String, Object>`. This map will contain all the object's properties and the four default: "`_id`" the _internal_ neo4j ID, "`_type`" that is the _type_ of the relationship, "`_startId`" that is the _internal_ neo4j Node ID where the relation starts from, "`_endId`" that is the _internal_ neo4j Node ID where the relation ends.

If the object is instead an `*instanceof* InternalPath` (thus being a neo4j Path) it will be also returned as an `ArrayList<Map<String, Object>>`. this list will contain an alternation of Node and Relationship converted following the below two lines' specifications.

IMPORTANT: You can't get an `InternalNode` or `InternalRelationship` directly `InternalPath`

When the object is not recognized as one of the two specified it is treated as a standard object and returned _directly_.

== Bolt module specific URL parameters ==

When using the jdbc Bolt module you will be able to specify dedicated parameters.
You can set them using a `Properties` object during the connection phase

----
DriverManager.getConnection(NEO4J_JDBC_BOLT_URL, PROPERTIES);
----

Here's a list of the keys you can use.

==== Trust Strategy ====
You can use the property `trust.strategy`, a string value of your choice among the `Config.TrustStrategy.Strategy` enum values.
When a file is required you *must* add the `trusted.certificate.file` property that *must* be a valid filename of the certificate file.

==== Flatten ====
When a ResultSet is flattened it explodes the returned columns (ONLY if they are ALL nodes and relationships) adding virtual columns with id, labels, type and entity specific fields.

You can enable such behaviour just by adding ?flatten=x to your url connection where x possible values are:

* -1: the entire resultSet is fetched (may slow down the performances with big resultSets) for retrieving nodes and relationships structure (useful if you're retrieving results with lots of different properties)

* N > 0: the specified number of rows are fetched for retrieving specific properties

Example:
Given a :User node connected to :Attributes nodes like (:Attribute {age:20})< -[:AGED]-(:User {username:"username"})-[FULL_NAME]- >(:Attribute {full_name:"Name Surname"})

with the query:

MATCH (u:User)--(a:Attribute) RETURN u, a;

you will have only the columns (u, a) with flattening disabled;

with flatten=1 you will have u, u.id, u.labels, u.username, a, a.id, a.type, a.age

with flatten=-1 you will have u, u.id, u.labels, u.username, a, a.id, a.type, a.age, a.full_name

=== Connection Acquisition Timeout ===
This setting limits the amount of time a session or transaction can spend waiting for a free connection to appear in the pool before throwing an exception.

Property key: `connection.acquisition.timeout`.

Value: amount of milliseconds (E.G: 60000)

For more information: https://neo4j.com/docs/developer-manual/current/drivers/client-applications/#driver-config-connection-pool-management[Connection pool management]

=== Max Connection Lifetime ===
How often the connection health is checked in the pool.

Property key: `max.connection.lifetime`.

Value: amount of minutes (E.G: 60)

For more information: https://neo4j.com/docs/developer-manual/current/drivers/client-applications/#driver-config-connection-pool-management[Connection pool management]

=== Max Connection Poolsize ===
The maximum number of connection in the pool.

Property key: `max.connection.poolsize`.

Value: number of connections (E.G: 50)

For more information: https://neo4j.com/docs/developer-manual/current/drivers/client-applications/#driver-config-connection-pool-management[Connection pool management]

=== Connection Liveness Check Timeout  ===
You normally should not need to tune this parameter. No connection liveliness check is done by default. Value 0 means connections will always be tested for validity and negative values mean connections will never be tested.

Property key: `connection.liveness.check.timeout`.

Value: the minimum idle time in milliseconds (E.G: 1000)

=== Connection Timeout ===
Specify socket connection timeout.

Property key: `connection.timeout`.

Value: the timeout duration in milliseconds (E.G: 1000)

For more information: https://neo4j.com/docs/developer-manual/current/drivers/client-applications/#driver-configuration-connection-timeout[Connection Timeout]

=== Encryption ===
Set to use encrypted/unencrypted traffic.

Property key: `encryption`.

Value: `true` or `false`

=== Leaked Session Logging ===
Enable logging of leaked sessions.

Property key: `leaked.sessions.logging`.

Value: `true` or `false`

=== Load Balancing Strategy ===
Provide an alternative load balancing strategy for the routing driver to use.

Property key: `load.balancing.strategy`

Value: `LEAST_CONNECTED` or `ROUND_ROBIN`

=== Max Transaction Retry Time ===
Specify the maximum time transactions are allowed to retry.

Property key: `max.transaction.retry.time`

Value: the timeout duration in milliseconds (E.G: 1000)


== Temporal functions ==
Since the 3.4 version you can get the temporal information stored in the database both as `java.sql.\*` typs and `java.time.*`.

These methods are implemented to get temporal data:

* `resultSet.getObject(int)` returns the `java.sql.` objects
* `resultSet.getObject(String)` returns the `java.sql.` objects
* `resultSet.getObject(int, Class)` returns the `java.time.` types, if you pass it.
* `resultSet.getObject(String, Class)` returns the `java.time.` types, if you pass it.
* `resultSet.getTimestamp` for `datetime()` and `localdatetime()`
* `resultSet.getDate` for `date()`
* `resultSet.getTime` for `time()` and `localtime()`

.Java types for neo4j temporal functions
|===
|java.time | neo4j | java.sql

|LocalDate | date() | Date

|LocalTime | localtime() | Time

|OffsetTime | time() | Time

|LocalDateTime | localdatetime() | Timestamp

|ZonedDateTime | datetime() | Timestamp

|===

=== Duration ===
The Duration concept is not in the JDBC specifications, so you can retrieve it using:

* `resultSet.getObject(int | String)` returns a `Map<String, Object>` with Long values for the keys: `'months', 'days','seconds', 'nanoseconds'`

* `resultSet.getObject(int | String, org.neo4j.driver.v1.types.IsoDuration.class)` returns the internal object.


=== Inside nodes, relationships or arrays ===
When you retrieve a Node, Relationship or an array, the internal object created by a temporal function contains
always a `java.sql` type value.

E.g:
```
ResultSet rs = statement.executeQuery("CREATE (e:Event {when: [localdatetime('2015-12-31T19:32:24')] }) RETURN e AS event");

rs.next();
Map<String, Object> map = (Map)rs.getObject(1);
Object whenField = map.get("when");
List whenList = (List) whenField;

java.sql.Timestamp when = (java.sql.Timestamp)whenList.get(0);
```

== Spatial functions ==
Since the 3.4 version you can get the spatial information stored in the database both as `Map`.

You can retrieve the spatial data using:

* `resultSet.getObject(int | String)` returns a `Map<String, Object>`
* `resultSet.getObject(int | String, org.neo4j.driver.v1.types.Point)` returns a `Point`

.Keys for Spatial functions
|===
|neo4j | keys(value)

| point({x, y}) | srid(7203), crs('cartesian'), x, y
| point({x, y, z}) | srid(9157), crs('cartesian-3d'), x, y, z
| point({latitude, longitude}) |  srid(4326), crs('wgs-84'), x, y, latitude, longitude
| point({latitude, longitude, height}) |  srid(4979), crs('wgs-84-3d'), x, y, z, latitude, longitude, height
|===

=== Inside nodes, relationships or arrays ===
When you retrieve a Node, Relationship or an array, the internal object created by a spatial function contains
always a `Map<String, Object>`

E.g:
```
ResultSet rs = statement.executeQuery("RETURN [point({ latitude: 12, longitude: 56, height: 4321 })] AS geo_3d");

rs.next();
Object points = rs.getObject(1);
List pointList = (List) points;
Map pointMap = (Map) point;
```
