!: BOLT 5.1

A: HELLO {"{}": "*"}
A: LOGON {"scheme": "basic", "principal": "neo4j", "credentials": "password"}
C: BEGIN {"db": "neo4j", "tx_type": "IMPLICIT", "[bookmarks]": "*", "[tx_metadata]": "*"}
   RUN "RETURN 1 as n" {} {}
   PULL {"n": 1000}
S: <SLEEP> 1
   SUCCESS {}
   <SLEEP> 1
   SUCCESS {"fields": ["n"]}
   <SLEEP> 1
   RECORD [1]
   <SLEEP> 1
   SUCCESS {"type": "r"}
C: COMMIT
S: <SLEEP> 1
   SUCCESS {}
C: GOODBYE
S: <EXIT>
