!: BOLT 5.1

C: HELLO {"{}": "*"}
S: SUCCESS {"server": "Neo4j/4.4.1", "hints": {"connection.recv_timeout_seconds": 1}, "connection_id": "bolt-1"}
A: LOGON {"scheme": "basic", "principal": "neo4j", "credentials": "password"}
C: BEGIN {"db": "neo4j", "tx_type": "IMPLICIT", "[bookmarks]": "*", "[tx_metadata]": "*"}
   RUN "RETURN 1 as n" {} {}
   PULL {"n": 1000}
S: SUCCESS {}
   SUCCESS {"fields": ["n"]}
   RECORD [1]
   SUCCESS {"type": "r"}
C: COMMIT
S: <SLEEP> 2
   SUCCESS {}
?: GOODBYE
