= Configuration

== Driver class name

The Neo4j JDBC Driver is `org.neo4j.jdbc.Neo4jDriver`.
In modern Java tools you should not have to touch this class directly, but there are some connection pools and front-ends that will ask you for this.
The class is public API.

We also provide `org.neo4j.jdbc.Neo4jDataSource` as `javax.sql.DataSource`.

== URL and connection properties

The canonical URL format for the Neo4j JDBC Driver is

[source, text]
----
jdbc:neo4j://<host>:<port>/<database>?param1=value1&param2=value2
----

The database name and any query parameters are optional and can be omitted.
All configuration arguments, can be passed either as query parameters or via a `java.util.Properties` object.
The latter is sometimes defined by tooling for you.
It's highly recommended to follow the JDBC spec, which discourages using any form of URL authentication.

TIP: There is no need to specify `bolt` or other additional prefixes in the URL, as a matter of fact: The driver does not support this.
     It does however support adding details about the transport being used:
     +
     `neo4j+s` enables encryption and only accepts SSL certificates from the server that are signed by a known certificate authority.
     `neo4j+ssc` enables encryption and accepts self-signed certificates (which must be added to the certificate store).

The driver accepts the following configuration arguments, either properties or as URL query parameters:

.Configuration arguments
|===
|Name|Type|Meaning|Default

|`timeout`
|`Integer`
|Timeout for connection acquisition in milliseconds
|`1000`

|`agent`
|`String`
|User agent
|`neo4j-jdbc`

|`enableSQLTranslation`
|`Boolean`
|Flag that enables automatic translation from SQL to Cypher (requires a translator on the classpath)
|`false`

|`cacheSQLTranslations`
|`Boolean`
|Flag that enables caching of translations. SQL translations are not "free", parsing of SQL costs a bit of time, and so does Cypher rendering. In addition, we might up look up metadata to be able to project individual properties. If this takes to long, any translation might be cached.
|`false`

|`rewritePlaceholders`
|`Boolean`
|Flag that allows you to use `?` as placeholders in *Cypher* statements (as required by JDBC). These will automatically be rewritten into `$1`, `$2` … `$n`, starting at 1, so that the numbering matches the 1-based JDBC index.
|Defaults to `true` when `enableSQLTranslation` is `false`, `false` otherwise

|`ssl`
|`Boolean`
|An optional flag that is an alternative to `neo4j+s`. It can be used for example to programmatically enable the full SSL chain.
|`null`

|`sslMode`
|`Enum<SSLMode>`
|An optional configuration for fine-grained control over SSL configuration. Allowed values are `disable`, `require`, `verify-full`.
|`null`

|`user`
|`String`
|The username (principal) to use for authentication. *NOT RECOMMENDED* for security reasons.
|`neo4j`

|`password`
|`String`
|The password (credentials) to use for authentication. *NOT RECOMMENDED* for security reasons.
|`password`

|===

== Getting a driver or a connection instance

NOTE: This section most likely only applies if you use the Neo4j JDBC Driver as part of application development in contrast to using it as part of front-end tool such as https://dbeaver.io[DBeaver], https://www.jetbrains.com/datagrip/[DataGrip] or UI-based ETL tools.

The easiest way to acquire a connection is directly through the `java.sql.DriverManager`.

[source, java, tabsize=4]
.Acquiring a JDBC connection towards Neo4j
----
include::{examplesDir}/Configuration.java[tag=cdm]
----

While our connection implementation is thread-safe, it does—as dictated by the JDBC Spec—only allow one concurrent transaction per connection.
For a multi-thread application you want to use a connection pool.
There's https://github.com/brettwooldridge/HikariCP[HikariCP], but usually application server and containers or frameworks bring their own.
It's safe to use any of them, as the Neo4j JDBC Driver does not do internal pooling.

If you need access to an instance of the Neo4j driver itself, you can use the following approach:

[source, java, tabsize=4]
.Acquiring an instance of the Neo4j JDBC Driver
----
include::{examplesDir}/Configuration.java[tag=ddm]
----

== Securing your connection by using SSL

The Neo4j JDBC Driver supports the same SSL option as the common Java driver does, with the same URL protocols, using `+s` or `+ssc` as additional indicators for the level of security that is required.

The same configuration can also be achieved with a URL query parameter or an entry in the properties passed to the `DriverManager` or driver instance when asking for a connection.
As long as you don't specify contradicting values, it's fine to combine both approaches.

=== Understanding the SSL mode

The possible settings are best explained using the available SSL modes.
The following list is ordered by ascending security:

* `disable` default, "I don’t care about security and don’t want to pay the overhead for encryption"
* `require` "I want my data to be encrypted, and I accept the overhead. I trust that the network will make sure I always connect to the server I want." (Server must support encryption, no hostname / CA validation is done, this is only secure on private networks, without going through the "hassle" of proper certificates and should not really be used over public internet)
* `verify-full` "I want my data encrypted, and I accept the overhead. I want to be sure that I connect to a server I trust, and that it’s the one I specify."

NOTE: The Neo4j JDBC Driver does not include revocation checks.

The most secure option can also be enabled by just using `ssl=true` either as query parameter or as property entry passed to the `DriverManager`.
This option corresponds to `neo4j+s`.
`require` on the other hand corresponds to `neo4j+ssc`.

You might wonder why using the additional enum: We might support additional modes in the future, such as letting the service decide about SSL, or being able to express a preference towards SSL without requiring it.

TIP: Neo4j cluster can offer both plain bolt connections and encrypted SSL connection or just one of them. So just because you can connect using `neo4j+s` does not mean that you cannot connect using just `neo4j` or vice versa. This is dependent on the setup of your database. Neo4js managed offering, https://neo4j.com/cloud/platform/aura-graph-database/[Neo4j AuraDB], only supports encrypted connection, so you _must_ use `+s`, `ssl=true` or `sslMode=verify-full`.

=== Valid URLs

The following URLs are all valid

`neo4j+s://xyz.databases.neo4j.io`:: Use full verification with the `xzy` instance at AuraDB
`neo4j://xyz.databases.neo4j.io?ssl=true`:: The same, but using the shorthand URL parameter
`neo4j://xyz.databases.neo4j.io?sslMode=verfiy-full`:: The same, but using the explicit mode
`neo4j+s://xyz.databases.neo4j.io?ssl=true&sslMode=verify-full`:: Not more secure, but does not fail on you
`neo4j+ssc://this.is.a.trustworthy.instance.for.sure.com`:: Trust whatever certificate and hostname there is, but do use SSL
`neo4j://my-testing-instance.local`:: Use a plain connection.

We only refuse contradicting values when you use several configuration mechanism:

* `+s` with `ssl=false` or `sslMode` set to `disable`
* `+ssc` with `ssl=false` or any `sslmode` not equal to `require`

In essence, you cannot express to use SSL and not use it at the same time.
The reason to offer several mechanism is that we want you to be able to use a fixed URL with dynamic query parameters or dynamic URLs or whatever way of configuring you prefer in a programmatic way.

=== Using .dotenv files

When you sign up for https://neo4j.com/cloud/platform/aura-graph-database/[Neo4j AuraDB] and create a database, you will be asked to download a text-file named similar to `Neo4j-9df57663-Created-2023-06-12.txt`. This is essentially a https://www.dotenv.org[.dotenv] file containing all necessary information required to connect to an aura Database.

These files can be directly used via `Neo4jDriver.fromEnv()`. This method exists in several overloads, which let you configure both filename and directory. Additionally, the builder behind it let's you configure options that are not usually contained in the files from AuraDB.
