= Neo4j specific conversions

Neo4j does not support all types used in the relational world.
For some of them we offer conversions that are also available in frameworks such as https://github.com/spring-projects/spring-data-neo4j[Spring Data Neo4j (SDN)].
Those conversions are available in this driver as well, so you could use both SDN and this driver interchangeably.

== Data types for fixed-point arithmetic

Neo4j does not support `BigInteger` and `BigDecimal`.
The only way to store them is as `String`, and to read them back into the corresponding type.
This is in line with SDN and OGM.

Any parameter of those types passed to `PreparedStatement` or `CallableStatement` will be stored as `String`, but can be read back through corresponding methods on the result sets.

== SQL Date, Time and Timestamps

`java.sql.Date`:: Maps to Cypher `DATE`
`java.sql.Time`:: Maps to Cypher `LOCAL TIME`
`java.sql.Timestamp`:: Maps to Cypher `LOCAL DATETIME`

For information on Cypher date types, see https://neo4j.com/docs/cypher-manual/current/values-and-types/temporal/[Temporal types].

For more precise a mapping, use a Neo4j https://neo4j.com/docs/api/java-driver/current/org.neo4j.driver/org/neo4j/driver/Value.html[`Value`] instance with the appropriate type and its methods `setObject` and `getObject`.
