= Distribution

== Driver modules and dependencies

The driver consists of 3 modules:

{artifact-id}::
This is the actual JDBC implementation for Neo4j

{artifact-id-spi}::
This is the SPI for the default SQL to Cypher translation implementation and for any further or custom implementation.

{artifact-id-impl}::
This is the *optional* default implementation of a SQL to Cypher translator.

IMPORTANT: If you just want to use the Neo4j JDBC Driver for running Cypher statements, the only module you need to think about is `{group-id}:{artifact-id}`, and in case you are developing in an environment with proper dependency management, this is all you need to declare.

While the translator SPI is a required dependency and pulled in via Maven or Gradle, the actual implementation is not.
This allows for

- The possibility to opt-out of having additional dependencies in all cases you are not using SQL to Cypher translation
- Requiring different JDK baselines or licensing modules for our implementations
- Allowing you to create alternative ways of creating a translator

=== Dependencies

We offer two "dependency free" modules, that shade everything into one binary artifact.
Those bundles should cover a lot of tooling, and we discuss those bundles below in <<available_bundles>>.
In case you are interested in the actual dependencies of the driver, those are the direct, compile-time dependencies of the driver:

.Dependency tree of the core driver.
[source,text]
----
org.neo4j.driver:neo4j-jdbc
+- io.netty:netty-handler
|  +- io.netty:netty-common
|  +- io.netty:netty-resolver
|  +- io.netty:netty-buffer
|  +- io.netty:netty-transport
|  +- io.netty:netty-transport-native-unix-common
|  \- io.netty:netty-codec
+- org.neo4j:neo4j-cypher-dsl-schema-name-support
+- org.neo4j.driver:neo4j-jdbc-translator-spi
----


[#available_bundles]
== Available bundles

All bundles of the Neo4j JDBC Driver are distributed on Maven Central.
The bundles have different characteristics that we will explain the following sections.
Depending on your use-case or your environment you pick one or the other bundle, but not several at once.


=== Individual components

Pick this distribution if you have an application that uses dependencies management in which you don't have to care about dealing with binary artifacts yourself.

For Maven you will want to use this dependency declaration:

[source,xml,subs="verbatim,attributes"]
.Maven dependency for the core Neo4j JDBC Driver artifact
----
<dependency>
    <groupId>{group-id}</groupId>
    <artifactId>{artifact-id}</artifactId>
    <version>{version}</version>
</dependency>
----

And for Gradle you would want to declare the following runtime dependency:

[source,groovy,subs="verbatim,attributes"]
.Neo4j JDBC Driver as Gradle runtime dependency
----
dependencies {
    runtimeOnly '{group-id}:{artifact-id}:{version}'
}
----

If you want to use the SQL to Cypher translation from Neo4j, you need to add the following dependency in your Maven build:

[source,xml,subs="verbatim,attributes"]
.Maven dependency for the default SQL to Cypher translator
----
<dependency>
    <groupId>{group-id}</groupId>
    <artifactId>{artifact-id-impl}</artifactId>
    <version>{version}</version>
</dependency>
----

and the same coordinates, but for Gradle:

[source,groovy,subs="verbatim,attributes"]
.Gradle dependency for the default SQL to Cypher translator
----
dependencies {
    runtimeOnly '{group-id}:{artifact-id-impl}:{version}'
}
----

[#small_bundle]
=== Small bundle

Pick this distribution if you work with ETL tools or tooling for relational databases that allow adding JDBC driver only as single artifacts or that make it unnecessary hard to add additional jars.
This bundle does not contain the default SQL to Cypher translator!
The coordinates of this bundle are `{group-id}:{artifact-id-bundle}` and you can download it from Maven central:

https://repo.maven.apache.org/maven2/org/neo4j/{artifact-id-bundle}/{version}/{artifact-id-bundle}-{version}.jar

TIP: All bundles can certainly be used as a normal project dependency as well. This might be useful for example if your project depends on another, potentially conflicting Netty version.

=== Full bundle

This bundle contains the default SQL to Cypher translator.
Otherwise, it is identical to the <<small_bundle, small bundle>>.
Its coordinates are `{group-id}:{artifact-id-full-bundle}` and you can download it from central here:

https://repo.maven.apache.org/maven2/org/neo4j/{artifact-id-full-bundle}/{version}/{artifact-id-full-bundle}-{version}.jar
