= Distribution

== Driver modules and dependencies

The driver consists of 3 modules:

{artifact-id}::
This is the actual JDBC implementation for Neo4j

{artifact-id-spi}::
This is the SPI for the default SQL-to-Cypher translation implementation and for any further or custom implementation.

{artifact-id-impl}::
This is the default and *optional* implementation of an SQL-to-Cypher translator.
It provides a somewhat opinionated approach of translating SQL statements into semantically equivalent Cypher statements.

IMPORTANT: If you just want to use the Neo4j JDBC Driver to run Cypher statements, you only need the module `{group-id}:{artifact-id}`. As long as you are developing in an environment with proper dependency management, this is all you need to declare.

While the translator SPI is a required dependency and gets pulled in via Maven or Gradle, the actual implementation is not.
This allows for:

- Opting out of having additional dependencies if you don't need the SQL-to-Cypher translation
- Requiring different JDK baselines or licensing modules for our implementations
- Allowing you to create alternative translators

=== Dependencies

There are two "dependency-free" modules, which shade everything into one binary artifact each.
Those bundles cover a lot of tooling (see <<available_bundles>>).

The driver's direct, compile-time dependencies are listed below:

.Dependency tree of the core driver
[source,text]
----
org.neo4j:neo4j-jdbc
+- io.github.cdimascio:dotenv-java
+- io.netty:netty-handler
|  +- io.netty:netty-common
|  +- io.netty:netty-resolver
|  +- io.netty:netty-buffer
|  +- io.netty:netty-transport
|  +- io.netty:netty-transport-native-unix-common
|  \- io.netty:netty-codec
+- org.neo4j:neo4j-cypher-dsl-schema-name-support
+- org.neo4j:neo4j-jdbc-translator-spi
----


[#available_bundles]
== Available bundles

All bundles of the Neo4j JDBC Driver are distributed on Maven Central.
The bundles have different characteristics: depending on your use-case or your environment, you can pick one or the other bundle, but not both at once.


=== Individual components

Pick this distribution if you have an application that uses dependencies management in which you don't have to care about dealing with binary artifacts yourself.

IMPORTANT: We offer a Maven BOM project, which you should import when using the individual modules, so that you have always a consistent set of versions. The coordinates are `{group-id}:neo4j-jdbc-bom`.

For Maven, use this dependency declaration:

[source,xml,subs="verbatim,attributes"]
.Maven dependency for the core Neo4j JDBC Driver artifact
----
<dependency>
    <groupId>{group-id}</groupId>
    <artifactId>{artifact-id}</artifactId>
    <version>{version}</version>
</dependency>
----

And for Gradle you would want to declare the following runtime dependency:

[source,groovy,subs="verbatim,attributes"]
.Neo4j JDBC Driver as Gradle runtime dependency
----
dependencies {
    runtimeOnly '{group-id}:{artifact-id}:{version}'
}
----

If you want to use the SQL-to-Cypher translation from Neo4j, you need to add the following dependency in your Maven build:

[source,xml,subs="verbatim,attributes"]
.Maven dependency for the default SQL to Cypher translator
----
<dependency>
    <groupId>{group-id}</groupId>
    <artifactId>{artifact-id-impl}</artifactId>
    <version>{version}</version>
</dependency>
----

and the same coordinates, but for Gradle:

[source,groovy,subs="verbatim,attributes"]
.Gradle dependency for the default SQL to Cypher translator
----
dependencies {
    runtimeOnly '{group-id}:{artifact-id-impl}:{version}'
}
----

[#small_bundle]
=== Small bundle

Pick this distribution if you work with ETL tools or tooling for relational databases that allow adding the JDBC driver only as single artifacts or that make it unnecessary hard to add additional jars.
This bundle does not contain the default SQL-to-Cypher translator!
The coordinates of this bundle are `{group-id}:{artifact-id-bundle}` and you can download it from Maven central:

https://repo.maven.apache.org/maven2/org/neo4j/{artifact-id-bundle}/{version}/{artifact-id-bundle}-{version}.jar

TIP: All bundles can be used as normal project dependencies as well.
This might be useful for example if your project depends on a different, potentially conflicting Netty version.

[#full_bunde]
=== Full bundle

This bundle contains the default SQL-to-Cypher translator.
Otherwise, it is identical to the <<small_bundle, small bundle>>.
Its coordinates are `{group-id}:{artifact-id-full-bundle}` and you can download it from Maven central here:

https://repo.maven.apache.org/maven2/org/neo4j/{artifact-id-full-bundle}/{version}/{artifact-id-full-bundle}-{version}.jar

[#text2cypher_bundle]
=== text2cypher bundle

We also ship a very experimental bundle that we call `text2cypher`:

https://repo.maven.apache.org/maven2/org/neo4j/{artifact-id-text2cypher-bundle}/{version}/{artifact-id-text2cypher-bundle}-{version}.jar

See xref:text2cypher.adoc[] more information.
