= Neo4j JDBC Driver
Michael Simons <michael.simons@neo4j.com>
:doctype: article
:lang: en
:listing-caption: Listing
:source-highlighter: coderay
:icons: font

ifndef::site-gen-antora[]
:examplesDir: ../examples
:group-id: ${groupId}
:artifact-id: ${mainArtifactId}
:artifact-id-spi: ${mainArtifactId}-translator-spi
:artifact-id-impl: ${mainArtifactId}-translator-impl
:artifact-id-bundle: ${mainArtifactId}-bundle
:artifact-id-full-bundle: ${mainArtifactId}-full-bundle
:version: ${project.version}
endif::[]

ifdef::site-gen-antora[]
:examplesDir: examples$
endif::[]

:copyright: Copyright 2023-2024 the original authors.

(C) {copyright}

[abstract]
== Abstract
This is the manual for the official Neo4j JDBC Driver.

This driver is officially supported and endorsed by Neo4j.
It is a standalone driver, independent of and *not* built on the https://github.com/neo4j/neo4j-java-driver[common Neo4j Java Driver].
While the latter provides a Neo4j-idiomatic way to access Neo4j from Java, the JDBC driver adheres to https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/java/sql/package-summary.html[JDBC 4.3].

== Introduction

The JDBC acronym stands for "Java Database connectivity" and as such is not tight exclusively to relational database.
Nevertheless, not only a lot of terms are tight somewhat to relational databases in general and SQL in detail, some of the behaviour defined is as well.
Neo4j is a graph database with quite a different paradigm than relational and a non-standardized behaviour in some areas.
There might be some details that don't map 100% in each place, and we make sure to educate you about these in this documentation

NOTE: Inside this documentation we will refer to *this* driver as the _Neo4j JDBC Driver_ and to the idiomatic Neo4j driver as the _common Neo4j Java Driver_.

The Neo4j JDBC Driver requires JDK 17 on the client side and a minimum version of Neo4j 5.5 on the server side.
To use it against a Neo4j cluster, server-side routing must be enabled on the cluster.

=== Features

* Adheres to JDBC 4.3
* Can run any Cypher statement
* Implements `DatabaseMetaData` and `ResultSetMetaData` as fully as possible with a nearly schemaless database and general very flexible result sets, allowing for automatic metadata retrieval from ETL and ELT tools
* Provides an https://en.wikipedia.org/wiki/Service_provider_interface[SPI] to hook in translators from SQL to Cypher
* Provides an optional default implementation to translate many SQL statements into semantically similar Cypher statements
* Does not do connection pooling and transaction management otherwise than dictated by the JDBC Spec

The absence of any connection pooling and transaction management is actually an advantage of the Neo4j JDBC Driver over the common Neo4j Java Driver.
It allows to pick and choose any database connection pooling system such as https://github.com/brettwooldridge/HikariCP[HikariCP] and transaction management such as https://jakarta.ee/specifications/transactions/[Jakarta Transactions].

NOTE: The default SQL to Cypher translation implementation is based on https://www.jooq.org[jOOQ] by https://www.datageekery.com[Datageekery].
We are a long-time fans of how Lukas Eder—inventor of jOOQ—has bridged the gap between Java and database querying.
It even inspired the https://github.com/neo4j-contrib/cypher-dsl[Cypher-DSL], providing the other half of our translation layer.
We are grateful for kick-starting the original Sql2Cypher project together in early 2023, on which we can build now.

=== When to use the Neo4j JDBC Driver?

This driver has been developed with the following use-cases in mind:

* Integration with ETL and ELT tools that don't offer an integration based on the common Neo4j Java driver
* An easier on-ramp towards Neo4j for teams that are familiar with JDBC and want to keep on using that API, but with Cypher and Neo4j
* Integration for ecosystems like Jakarta EE whose transaction management will directly support any compliant JDBC driver
* Integration with database migration tools such as Flyway

There is *no need* to redesign an application that is build on the common Neo4j Java Driver to use this driver.
If your ecosystem already provides a higher-level integration based on the common Neo4j Java Driver, such as https://github.com/spring-projects/spring-data-neo4j[Spring Data Neo4j (SDN)] for https://spring.io/projects/spring-boot/[Spring], there is no need to switch to something else.
In case of https://quarkus.io[Quarkus] the Neo4j JDBC Driver is an option to consider: While we do provide an integration for the https://github.com/quarkiverse/quarkus-neo4j[common Neo4j Java Driver], this integration does not support Quarkus' transaction systems in contrast to his driver.

While there is little incentive to use this driver with Hibernate (https://github.com/neo4j/neo4j-ogm[Neo4j-OGM] or SDN are the better alternatives for Neo4j), it might be worth giving https://spring.io/projects/spring-data-jdbc/[Spring Data JDBC] a try.

=== About this documentation

In this documentation we will focus on getting and configuring the Neo4j JDBC Driver and enabling optional features.
We will discuss the design choices made in the metadata retrieval and how we map Neo4j labels to tables as well as our opinionated choices with regards the automatic SQL to Cypher translation.

While we do provide runnable examples that due to their nature will show how to use JDBC in general, this is not a documentation about how to correctly use JDBC as an API.

ifndef::site-gen-antora[]
include::quickstart.adoc[leveloffset=+1]

include::distribution.adoc[leveloffset=+1]

include::configuration.adoc[leveloffset=+1]
endif::[]
