= Quickstart

Add the JDBC driver to your application, for example as a Gradle dependency:

[source, kotlin, subs="verbatim,attributes"]]
.Using the full bundle as a runtime dependency inside a Gradle based project
----
dependencies {
    runtimeOnly({group-id}:{artifact-id-full-bundle}:{version})
}
----

With that in place, you can use the JDBC driver for Neo4j as you would do with any other JDBC driver.

[source, java, tabsize=4]
.Acquire a connection using the JDBC driver and execute a query
----
include::{examplesDir}/Quickstart.java[tag=pt1]
----
<.> Get a JDBC connection, no need to do any class loading beforehand, the driver will be automatically registered
<.> Create a reusable statement
<.> Immediate execute a query on it
<.> Iterate the results like you would do with any other JDBC result set
<.> JDBC is index 1 based
<.> JDBC also allows retrieval of result columns by name; the Neo4j JDBC driver also supports complexe objects such as lists

In the example above we used Neo4j's lingua franca, https://neo4j.com/docs/getting-started/cypher-intro/[Cypher], to query Neo4j.
The Neo4j JDBC Driver has limited support for using SQL as well.
It will do so automatically or on a case by case basis.
For the latter you can use `java.sql.Connection#nativeSQL(String)` and use the result in your queries
For automatic translation instantiate the driver using an additional URL parameter, `sql2cypher` set to `true`.
The following example shows how:

[source, java, tabsize=4, indent=0]
.Configure the JDBC driver to automatically translate SQL to cypher.
----
include::{examplesDir}/Quickstart.java[tag=pt2]
----
<.> This SQL query will be translated into the same Cypher query shown before, the remainder of the method is identical to before.

TIP: In case any tooling asks you for the name of the concrete driver class, it is: `org.neo4j.driver.jdbc.Neo4jDriver`.

We will cover the SQL to Cypher translation in detail later in this manual.

The JDBC Spec does not support named parameters, only index based parameters.
Indexes start at `1` in SQL.
So for all `PreparedStatement` instances you would want to specify your parameters like this:

[source, java, tabsize=4, indent=0]
.Using parameters with a `PreparedStatement`
----
include::{examplesDir}/NamedParameters.java[tag=index]
----

This is independent of the SQL to Cypher translation mechanism:

[source, java, tabsize=4, indent=0]
.Using parameters with a `PreparedStatement` (SQL variant)
----
include::{examplesDir}/NamedParameters.java[tag=index-sql]
----

You can downcast the `PreparedStatement` to `Neo4jPreparedStatement`.
This JDBC extension will let you use named parameters:

[source, java, tabsize=4, indent=0]
.Using named parameters with the `Neo4jPreparedStatement`
----
include::{examplesDir}/NamedParameters.java[tag=index-np]
----

== Getting a connection via environment variables

If you are happy to depend on `org.neo4j.driver.jdbc.Neo4jDriver` directly and want to get a connection as easy as possible, you might want to use `fromEnv`:

[source, java, tabsize=4, indent=0]
.Get a connection from the environnment.
----
include::{examplesDir}/Quickstart.java[tag=pt3]
----
<.> Notice how we directly use the concrete driver class here and how the methods returns an optional: If we don't find the required properties, we can't create a connection.

The `fromEnv` looks for a couple of specific system environment variables and it will be true to the principles of the https://12factor.net[12 factor app] while doing so:

- It will look in the System environment first
- It will then look for a file named `.env` in the current working directory

There are overloads that let you configure the directory and the filename to look for.
The properties we support are as follows:

`NEO4J_URI`:: The address or URI of the instance to connect to</li>
`NEO4J_USERNAME`:: Optional username
`NEO4J_PASSWORD`:: Optional password
`NEO4J_SQL_TRANSLATION_ENABLED`:: Optional flag to enable full SQL to Cypher translation, defaults to `false`

NOTE: Information from both the System environment and the .env files are combined. If for example `NEO4J_SQL_TRANSLATION_ENABLED` is in the System environment but not in the .env file, it will still be picked up.

This feature is especially useful with Neo4j AuraDB.
When creating a new AuraDB instance you are required to download an `.env` file and you can directly use it with the Neo4j JDBC Driver like this:

[source,java]
.Using a .env file from AuraDB
----
try (
    var con = Neo4jDriver.fromEnv("Neo4j-cb3d8b2d-Created-2024-02-14.txt")
        .orElseThrow();
    var stmt = con.createStatement();
    var movies = stmt.executeQuery("MATCH (n:Movie) RETURN n.title AS title")
) {
    while (movies.next()) {
        System.out.println(movies.getString("title"));
    }
}
----