[#text2cypher]
= text2cypher

== Introduction

This is an experimental translator inspired by the Neo4j Labs project https://github.com/neo4j-labs/text2cypher[text2cypher].

If you add this translator to the classpath or use the <<text2cypher_bundle,text2cypher bundle>>, all queries that start with

[source,txt]
----
🤖,
----

will be treated as _natural language_ queries written in *plain english*.
The driver will strip the prefix, and use https://openai.com[OpenAI] to translate the input into a Cypher statement.
The driver will augment the generation of the query by passing the current graph schema along with the input question.

[WARNING]
====
The following data will be sent to an external API:

* Your database schema, including label names
* Any natural language query

Don't use this translator if you don't want the above, or are not allowed to do so.
====

This module requires one additional configuration: the OpenAI API key.
You can use either a URL parameter, a JDBC property entry, or an environment variable:

* URL parameter/property name is `openAIApiKey`
* Environment variable name is `OPEN_AI_API_KEY`

[source,txt]
.Example of a valid URL
----
jdbc:neo4j://localhost:7687?openAIApiKey=sk-xxx-your-key
----

With that in place, a query such as the following can be translated into Cypher:

[source,txt]
----
🤖, How was The Da Vinci Code rated?
----

The outcome of the LLM is not deterministic and will most likely vary.
While you can execute it directly, we strongly recommend to use `Connection#nativeSQL` to retrieve the Cypher statement, inspect it, and then run it separately.

NOTE: Once a natural language query gets translated into Cypher, the result will be cached and further invocations of that query will use the cached result.

All that statements that do not start with 🤖 will be used as-is and treated as Cypher.

Get the full, ready to use bundle here: https://repo.maven.apache.org/maven2/org/neo4j/{artifact-id-text2cypher-bundle}/{version}/{artifact-id-text2cypher-bundle}-{version}.jar. More information in xref:distribution.adoc#available_bundles[Available bundles].
