= Usage

Add the JDBC driver to your application, for example as a Gradle dependency:

[source, kotlin, subs="verbatim,attributes"]]
.Using the full bundle as a runtime dependency inside a Gradle-based project
----
dependencies {
    runtimeOnly({group-id}:{artifact-id-full-bundle}:{version}) // <.>
}
----
<.> The coordinates are the same for a Maven project.

You can then use the Neo4j JDBC driver as you would do with any other JDBC driver:

include::README.adoc[tag=quickstart]

For more information, see xref:sql2cypher.adoc#s2c_introduction[SQL to Cypher translation].

The JDBC specification does not support named parameters, only index-based parameters, starting at `1`.
So for all `PreparedStatement` instances you need to specify parameters like this:

[source, java, tabsize=4, indent=0]
.Using parameters with a `PreparedStatement`
----
include::{examplesDir}/java/NamedParameters.java[tag=index]
----

This is independent of the SQL-to-Cypher translation mechanism:

[source, java, tabsize=4, indent=0]
.Using parameters with a `PreparedStatement` (SQL variant)
----
include::{examplesDir}/java/NamedParameters.java[tag=index-sql]
----

To use named parameters, downcast the `PreparedStatement` to `Neo4jPreparedStatement`.

[source, java, tabsize=4, indent=0]
.Using named parameters with a `Neo4jPreparedStatement`
----
include::{examplesDir}/java/NamedParameters.java[tag=index-np]
----

[#connect-dotenv]
== Getting a connection via environment variables

If you are happy to depend directly on `org.neo4j.jdbc.Neo4jDriver` and want to get a connection as easy as possible, you might want to use `fromEnv`:

[source, java, tabsize=4, indent=0]
.Get a connection from environment variables
----
include::{examplesDir}/java/Quickstart.java[tag=pt3]
----
<.> Notice how we directly use the concrete driver class here and how the methods return an optional: no connection can be created if the required connection variables are not found.

The `fromEnv` method looks for a few specific system environment variables and it adheres to the https://12factor.net[12 factor app] principles:

- First, it looks in the system environment
- Second, it looks for a file named `.env` in the current working directory. There are overloads that let you configure the directory and the filename to look for.

The supported variables are:

`NEO4J_URI`:: The address or URI of the instance to connect to.
`NEO4J_USERNAME`:: (Optional) Username.
`NEO4J_PASSWORD`:: (Optional) Password.
`NEO4J_SQL_TRANSLATION_ENABLED`:: (Optional) Whether to enable full SQL-to-Cypher translation, defaults to `false`.

NOTE: Information from both the system environment and the .env files are combined.
If for example `NEO4J_SQL_TRANSLATION_ENABLED` is in the system environment but not in the .env file, it will still be picked up.
Given the order of priority, information in the system environment always has precedence over the .env file.

This feature is especially useful with Neo4j AuraDB.
When creating a new AuraDB instance, you download a `.env` file that you can directly use with the Neo4j JDBC Driver:

[source,java]
.Using a .env file from AuraDB
----
try (
    var con = Neo4jDriver.fromEnv("Neo4j-cb3d8b2d-Created-2024-02-14.txt")
        .orElseThrow();
    var stmt = con.createStatement();
    var movies = stmt.executeQuery("MATCH (n:Movie) RETURN n.title AS title")
) {
    while (movies.next()) {
        System.out.println(movies.getString("title"));
    }
}
----
